"""empty message

Revision ID: 5e68925acc1e
Revises: 54970d700d80
Create Date: 2025-12-04 20:10:57.448279

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5e68925acc1e'
down_revision = '54970d700d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['tg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'tg_id')
    op.drop_column('questions', 'date')
    # ### end Alembic commands ###