name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy admin_bot and user_bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd ~/chgk_helper
            git pull
            # docker-compose stop admin_bot user_bot polls_bot
            # docker-compose rm -f admin_bot user_bot polls_bot
            docker-compose up -d --build admin_bot user_bot polls_bot
      - name: Deploy webserver
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.POLLS_SERVER_HOST }}
          username: ${{ secrets.POLLS_SERVER_USER }}
          key: ${{ secrets.POLLS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.POLLS_SERVER_PORT || 22 }}
          script: |
            cd ~/chgk_helper
            git pull
            # docker-compose stop webserver
            # docker-compose rm -f webserver
            docker-compose up -d --build webserver